name: CI/CD Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest mlflow numpy

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: minheintun/ml_a3:latest
      
      - name: Deploy to School Server via SSH (Docker Compose)

        uses: appleboy/ssh-action@v0.1.6
        with:
            host: ${{ secrets.MLBRAIN }}
            username: ${{ secrets.USERNAME_MLBRAIN }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
            proxy_host: ${{ secrets.BAZOOKA }}
            proxy_username: ${{ secrets.USERNAME_BAZOOKA }}
            proxy_key: ${{ secrets.PRIVATE_KEY }}
            proxy_passphrase: ${{ secrets.SSH_PASSPHRASE }}
        
            before_script: |
              echo "Connected to mlbrain ✅"
              cd st125064_03
        
            script: |
              docker compose down
              docker compose up -d
        

      # - name: Deploy to School Server via SSH (Docker Compose)
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.MLBRAIN }}
      #     username: ${{ secrets.USERNAME_MLBRAIN }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     proxy_host: ${{ secrets.BAZOOKA }}
      #     proxy_username: ${{ secrets.USERNAME_BAZOOKA }}
      #     proxy_key: ${{ secrets.PRIVATE_KEY }}
      #     proxy_passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     before_script:
            
      #     script: |
      #       docker compose down
      #       docker compose up -d
      #   env:
      #     SSH_CONFIG: ${{ github.workspace }}/config/ssh_config
